export const INITIAL_FILTERS = {
  title: false,
  body: false,
  emphasis: false,
  thumbnail: false,
  caption: false,
  ppt: false,
  cardNews: false,
  poster: false,
  batang: false,
  dotum: false,
  gothic: false,
  headline: false,
  handwriting: false,
  round: false,
  angular: false,
  simple: false,
  bold: false,
  flashy: false,
  cute: false,
  unique: false,
  classic: false,
  retro: false,
  free: false,
  emotional: false,
  distinct: false,
  strong: false,
  print: false,
  web: false,
  package: false,
  video: false,
  embedding: false,
  brand: false,
  ofl: false,
};

export type FilterKey = keyof typeof INITIAL_FILTERS;
export type Filters = Record<FilterKey, boolean>;
